package enums;

public enum RemoteOperation {
  CREATE_ACCOUNT, AUTHENTICATE, CREATE_CAR,
  UPDATE_CAR, PATCH_CAR_QUANTITY,
  DELETE_CAR, LIST_ALL_CARS, LIST_ALL_CARS_BY_CATEGORY,
  SEARCH_CAR, GET_QUANTITY_OF_CARS_STORED, BUY_CAR
}
